#!/usr/bin/env python2

import argparse
import os
import os.path
import random
import sys

parser = argparse.ArgumentParser(
    description='Echo N random PDB entries from a PDB database.',
    formatter_class=argparse.ArgumentDefaultsHelpFormatter)
aa = parser.add_argument
aa('--pdb-dir', dest='pdb_dir', type=str, default='/data/bio/pdb',
   metavar='PDB_DIR', help='The location of the PDB directory.')
aa('-n', dest='n', type=int, default=10,
   metavar='NUM_ENTRIES', help='The number of PDB entries to echo.')
aa('--just-ids', dest='just_ids', action='store_true',
   help='When set, only the PDB id codes will be printed.')
conf = parser.parse_args()

entries = []
for dpath, _, fnames in os.walk(conf.pdb_dir):
    for fname in filter(lambda s: s.endswith('.ent.gz'), fnames):
        entries.append(os.path.join(dpath, fname))

for fpath in random.sample(entries, conf.n):
    if conf.just_ids:
        noext = fpath[:-7]
        print noext[-4:]
    else:
        print fpath

